### ISSUE TITLE
Import error from oscilloscope

### ISSUE THREAD

**Issue by digital-cinema-arts** [pycampers/oscilloscope#12]
(using Python 3.9.1)

>>> from oscilloscope import Osc
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/zproc/serializer.py", line 33, in dumps_fn
    fn_bytes = _fn_dump_cache[fn_hash]
KeyError: 7688705624893688860

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/oscilloscope.py", line 7, in <module>
    import zproc
  File "/usr/local/lib/python3.9/site-packages/zproc/__init__.py", line 21, in <module>
    def increase(state, key, step=1):
  File "/usr/local/lib/python3.9/site-packages/zproc/state/state.py", line 564, in atomic
    Msgs.info: serializer.dumps_fn(fn),
  File "/usr/local/lib/python3.9/site-packages/zproc/serializer.py", line 35, in dumps_fn
    fn_bytes = cloudpickle.dumps(fn)
AttributeError: module 'cloudpickle.cloudpickle' has no attribute 'dumps'

**Comment by digital-cinema-arts** [comment]
Fixed from reading the other post about the same error.  :-)
