### ISSUE TITLE
No module named '_tkinter'

### ISSUE THREAD

**Issue by kracon7** [pycampers/oscilloscope#2]
I'm using ubuntu 16.04 and python 3.6
Got an error saying "No module named '_tkinter' " but I already had the latest version of tk installed. 
Thanks in advance if anyone could help!

(mujoco) jc@jc-XPS-15: /mujoco_ws/test_xmls $ sudo apt install python3-tk
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-tk is already the newest version (3.6.5-3~16.04.york4).
0 upgraded, 0 newly installed, 0 to remove and 21 not upgraded.

(mujoco) jc@jc-XPS-15:/mujoco_ws/test_xmls $ python 
Python 3.6.7 (default, Oct 25 2018, 09:16:13) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from oscilloscope import Osc
Traceback (most recent call last):
  File "/usr/lib/python3.6/tkinter/__init__.py", line 37, in <module>
    import _tkinter
ModuleNotFoundError: No module named '_tkinter'

>>> During handling of the above exception, another exception occurred:

>>>Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jc/virtualenvs/mujoco/lib/python3.6/site-packages/oscilloscope.py", line 5, in <module>
    import matplotlib.pyplot as plt
  File "/home/jc/virtualenvs/mujoco/lib/python3.6/site-packages/matplotlib/pyplot.py", line 2372, in <module>
    switch_backend(rcParams["backend"])
  File "/home/jc/virtualenvs/mujoco/lib/python3.6/site-packages/matplotlib/pyplot.py", line 207, in switch_backend
    backend_mod = importlib.import_module(backend_name)
  File "/home/jc/virtualenvs/mujoco/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/jc/virtualenvs/mujoco/lib/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 1, in <module>
    from . import _backend_tk
  File "/home/jc/virtualenvs/mujoco/lib/python3.6/site-packages/matplotlib/backends/_backend_tk.py", line 5, in <module>
    import tkinter as Tk
  File "/usr/lib/python3.6/tkinter/__init__.py", line 39, in <module>
    raise ImportError(str(msg) + ', please install the python3-tk package')
ImportError: No module named '_tkinter', please install the python3-tk package
>>>

**Comment by devxpy** [comment]
Does this work for you? https://stackoverflow.com/questions/15884075/tkinter-in-a-virtualenv

**Comment by kracon7** [comment]
https://stackoverflow.com/a/41687024
The second answer worked for me. 
Thanks!
